feat: add argo workflows
kubefirst/metaphor-go-template pull request #1
Opened 2022-08-09 12:51 UTC by converge

Signed-off-by: João Vanzuita <joao@kubeshop.io>

2022-08-10 19:12 UTC, pagottoo requested changes

2022-08-10 19:58 UTC, converge commented on charts/metaphor-go/templates/serviceaccount.yaml
> +{{- end -}}
thanks!

2022-08-12 11:16 UTC, 6za approved these changes

2022-08-12 11:18 UTC, pagottoo approved these changes
lgtm

2022-08-12 11:19 UTC, merged